const GLOBAL_ADMIN = "GLOBAL_ADMIN";
const TEAM_ADMIN = "TEAM_ADMIN";
const TEAM_MEMBER = "TEAM_MEMBER";
const USER_ROLE = "USER_ROLE";

const ROLES = [USER_ROLE, TEAM_MEMBER, TEAM_ADMIN, GLOBAL_ADMIN];

module.exports = {
  ROLES,
  USER_ROLE,
  TEAM_MEMBER,
  TEAM_ADMIN,
  GLOBAL_ADMIN,
};
