const ADMIN_ROLE = "ADMIN_ROLE";
const MOD_ROLE = "MOD_ROLE";
const MEMBER_ROLE = "MEMBER_ROLE";
const USER_ROLE = "USER_ROLE";

const ROLES = [USER_ROLE, MEMBER_ROLE, MOD_ROLE, ADMIN_ROLE];

module.exports = {
  ROLES,
  USER_ROLE,
  MEMBER_ROLE,
  MOD_ROLE,
  ADMIN_ROLE,
};
